// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvqejgqadicqeghgoybn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2cWVqZ3FhZGljcWVnaGdveWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMjc3OTksImV4cCI6MjA1NTkwMzc5OX0.SCairRT-hy0-tdVb-b3qmxifmKrQzs2KU-1-ID4z0es";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);